CREATE USER '$SQL_ROOT_USER'@'%' IDENTIFIED BY '$SQL_ROOT_PWD'
GRANT ALL PRIVILEGES ON * . * TO '$SQL_ROOT_USER'@'%'
FLUSH PRIVILEGES
CREATE DATABASE IF NOT EXISTS $SQL_DB
CREATE USER '$SQL_BASIC_USER'@'mariadb'
GRANT ALL PRIVILEGES ON $SQL_DB . * TO '$SQL_BASIC_USER'@'mariadb'
FLUSH PRIVILEGES

DELETE FROM mysql.user WHERE user=''
DELETE FROM mysql.user WHERE user='root'
FLUSH PRIVILEGES
