version: "2.2"
services:
  nginx:
    image: "nginx"
    ports:
      - "5000:80"
    networks:
      - front-end
  wordpress:
    image: "wordpress"
    networks:
      - front-end
      - back-end
  MariaDB:
    image: "mariadb"
    networks:
      - back-end
networks:
  front-end:
  back-end:
