version: "2.2"
services:
  MariaDB:
    image: "mariadb"
    container_name: db_inception
    networks:
      - back-end
  wordpress:
    image: "wordpress"
    container_name: wordpress_inception
    networks:
      - front-end
      - back-end
    depends_on:
      - MariaDB
  nginx:
    build: ./requierements/nginx
    container_name: nginx_inception
    ports:
      - "443:443"
    networks:
      - front-end
    depends_on:
      - wordpress
networks:
  front-end:
  back-end:
